url: http://wiki.ljhero.info
title: Wiki Â· Ljhero
keywords: wiki, makrdown, linux, python, cpp, security, simiki
description: "Ljhero's personal wiki, powered by simiki  and markdown. Focus on Python, C/C++, Linux, Software Security, Virtulization, and so on."
author: Ljhero
theme: yasimple
